spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gongmo?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1
    driver-class-name: com.mysql.jdbc.Driver

    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: IMB-AC-HikariCP-POOL
      max-lifetime: 2000000
      connection-timeout: 30000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  mybatis:
    mapper-locations: classpath:/mappers/*.xml
#  jpa:
#    hibernate:
#      connection:
#        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
#    properties:
#      hibernate:
#        default_schema: gfs
#        show_sql: false
#        format_sql: true
#        use_sql: true
#        hbm2ddl.auto: update
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        enable_lazy_load_no_trans: true
#        use_sql_comments: true
#        jdbc:
#          lob:
#            non_contextual_creation: true

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  main:
    allow-bean-definition-overriding: true
